### PR TITLE
Better handling of unexpected results.

### PR DESCRIPTION
**Pull request by markdoliner-doma**
The underwriter_staging_smoke job occassionally fails in circleci because this script reaches the 10 minute timeout (example: https://circleci.com/gh/StatesTitle/underwriter/12345). The script that's used to run the runscope api tests doesn't handle unexpected responses well so it's hard to tell based on the output alone if it's failing because the runscope tests are taking longer than 10 minutes or because there's some other unexpected response.

I mean, I assume the tests are just taking longer than 10 minutes? But I really have no idea. I'm not familiar with any of this, I just saw the failed circleci job and got curious.

I also moved the deadline check into the while loop because it's a little simpler. I think it makes it more obvious when the script exits due to timeout.

I tested these changes locally a bit and they seem ok.

I know this script was forked from an upstream project. It looks like States Title has made other changes to this script in our fork that don't exist upstream. I'm not planning on trying to contribute these changes upstream, but please let me know if people think that's important.

### CODE REVIEW

**Comment by ddemetri** [comment]
FYI - this is a public repo. You may not want these ST-specific comments in the public record :)

**Comment by markdoliner-doma** [comment]
@ddemetri Good point, thanks for mentioning. I'm not sure there's much I can do about it (and the info isn't super sensitive), but will investigate.

**Review by schavery — APPROVED** [review]
I don't think the information you exposed in the description of this PR is too influential. We had to make this repo public so that we could pull it in the build process, but we could make it private and add auth to the build process so that we're all buttoned up - we already have to have access to the states title repos in the build so it shouldn't be too difficult

**Comment by ddemetri** [comment]
I agree with @schavery. P.S. Hi @schavery !

**Comment by markdoliner-doma** [comment]
Cool, thanks @schavery and @ddemetri. FYI when I squashed and merged I changed the commit message to be a little more appropriate for merging upstream.

**Pull request merged**
